### ISSUE TITLE
[Documentation / main README] Would it be possible to clarify whether the most recent ImageMagick versions have support for jpeg-xl already?

### ISSUE THREAD

**Issue by rubyFeedback** [ImageMagick/jpeg-xl#1]
Would it be possible to clarify whether the most recent ImageMagick versions have support for jpeg-xl already?

I read news lately about jpeg-xl but right now I do not know whether ImageMagick supports it in its most
recent releases. Would it be possible to either add a FAQ, or just a short clarification whether ImageMagick
as of right now, supports jpeg-xl? I'd love to test the new format but I have also become a bit lazy and conservative
so I mostly just tend to what ImageMagick offers by default (it's my swiss army knife for image-related stuff
similar to ffmpeg for multimedia data).

**Comment by dlemstra** [comment]
There is support for jpeg-xl but you will need to enable it yourself because the library that we use is currently in alpha. I hope you have email responses enabled because issues should not be enabled in this repository.
